# General Jekyll Config
url: http://nullpointer.dk

# Handling reading
exclude: [CNAME, .gitignore, Gemfile, Gemfile.lock]
encoding: "utf-8"

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
timezone: "Europe/Copenhagen"
