# General Jekyll Config
url: http://nullpointer.dk

# Run in safe mode like github pages is.
safe: true

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Handling reading
exclude: [CNAME, .gitignore, Gemfile, Gemfile.lock]
encoding: "utf-8"

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
timezone: "Europe/Copenhagen"
