# General Jekyll Config
url: http://nullpointer.dk

# Handling reading
exclude: [CNAME, .gitignore, Gemfile, Gemfile.lock]
encoding: "utf-8"

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
timezone: "Europe/Copenhagen"

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
